/**
 * Supervises the upstream local agent service.
 *
 * By default the gateway is a pure client: you run `codebuddy --serve` yourself.
 * With `upstream.autoStart` enabled it instead spawns the bundled CodeBuddy CLI,
 * waits until it is healthy, picks up the gateway password it generates, and
 * restarts it if it dies.
 *
 * This is what makes auth env vars such as CODEBUDDY_API_KEY work: the child
 * inherits the gateway's environment (plus anything in `upstream.env`).
 */
import { spawn } from 'node:child_process';
import fs from 'node:fs';

import { readGatewayPassword } from './config.js';

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

export class UpstreamSupervisor {
  constructor({ config, upstream, log }) {
    this.cfg = config;
    this.upstream = upstream;
    this.log = log;
    this.child = null;
    this.restarts = 0;
    this.stopping = false;
    this.startedByUs = false;
    this.lastExit = null;
  }

  get enabled() {
    return Boolean(this.cfg.upstream.autoStart);
  }

  /** Probe the upstream health endpoint. */
  async probe(timeoutMs = 4000) {
    try {
      const res = await fetch(`${this.upstream.baseUrl}/api/v1/health`, {
        headers: this.upstream.headers(),
        signal: AbortSignal.timeout(timeoutMs)
      });
      if (!res.ok) return null;
      const body = await res.json().catch(() => null);
      return body?.data ?? body;
    } catch {
      return null;
    }
  }

  /**
   * Make sure an upstream is reachable.
   * @returns {Promise<{ok:boolean, started:boolean, detail:string}>}
   */
  async ensureRunning() {
    const existing = await this.probe();
    if (existing) {
      return { ok: true, started: false, detail: `already running (pid ${existing.pid ?? '?'})` };
    }

    if (!this.enabled) {
      return {
        ok: false,
        started: false,
        detail:
          'upstream is not reachable and upstream.autoStart is disabled. ' +
          'Start it manually with `codebuddy --serve`, or pass --spawn-upstream.'
      };
    }

    if (!this.cfg.upstream.cliPath) {
      return { ok: false, started: false, detail: 'CodeBuddy CLI not found; set --cli-path or CODEBUDDY_CLI_PATH' };
    }

    return this.#spawnAndWait();
  }

  async #spawnAndWait() {
    const port = this.cfg.upstream.servePort;
    const args = [
      this.cfg.upstream.cliPath,
      '--serve',
      '--port',
      String(port),
      '--host',
      '127.0.0.1',
      ...this.cfg.upstream.serveArgs
    ];

    this.log.info(`starting upstream agent service: ${this.cfg.upstream.cliPath} --serve --port ${port}`);
    this.child = spawn(process.execPath, args, {
      stdio: ['ignore', 'pipe', 'pipe'],
      env: { ...process.env, ...this.cfg.upstream.env },
      detached: false
    });
    this.startedByUs = true;

    let stderrTail = '';
    this.child.stderr?.on('data', (d) => {
      stderrTail = `${stderrTail}${d}`.slice(-2000);
      if (this.cfg.logLevel === 'debug') this.log.debug(`[upstream] ${String(d).trim()}`);
    });
    this.child.stdout?.on('data', (d) => {
      if (this.cfg.logLevel === 'debug') this.log.debug(`[upstream] ${String(d).trim()}`);
    });

    this.child.on('exit', (code, signal) => {
      this.lastExit = { code, signal, at: Date.now() };
      if (this.stopping) return;
      this.log.warn(`upstream exited (code=${code} signal=${signal})`);
      this.#scheduleRestart();
    });

    // Wait for health.
    const deadline = Date.now() + this.cfg.upstream.startTimeoutMs;
    while (Date.now() < deadline) {
      if (this.child.exitCode !== null) {
        return {
          ok: false,
          started: false,
          detail: `upstream exited during startup (code ${this.child.exitCode}). ${stderrTail.trim().slice(0, 300)}`
        };
      }
      const health = await this.probe(2500);
      if (health) {
        this.#adoptPassword();
        this.restarts = 0;
        return { ok: true, started: true, detail: `started on port ${port} (pid ${health.pid ?? this.child.pid})` };
      }
      await sleep(500);
    }

    return {
      ok: false,
      started: false,
      detail: `upstream did not become healthy within ${this.cfg.upstream.startTimeoutMs}ms. ${stderrTail.trim().slice(0, 300)}`
    };
  }

  /**
   * `codebuddy --serve` generates its gateway password on first start and writes
   * it to ~/.codebuddy/settings.json. Pick it up so we can authenticate.
   */
  #adoptPassword() {
    const fresh = readGatewayPassword();
    if (fresh && fresh !== this.upstream.password) {
      this.upstream.password = fresh;
      this.cfg.upstream.password = fresh;
      this.log.info('adopted the gateway password generated by the upstream service');
    }
  }

  #scheduleRestart() {
    if (this.restarts >= this.cfg.upstream.maxRestarts) {
      this.log.error(`giving up on the upstream after ${this.restarts} restarts`);
      return;
    }
    this.restarts += 1;
    const delay = Math.min(1000 * 2 ** (this.restarts - 1), 30_000);
    this.log.info(`restarting upstream in ${delay}ms (attempt ${this.restarts}/${this.cfg.upstream.maxRestarts})`);
    setTimeout(() => {
      if (this.stopping) return;
      this.#spawnAndWait().catch((err) => this.log.error(`upstream restart failed: ${err.message}`));
    }, delay).unref();
  }

  /**
   * Check that the gateway password we hold is accepted by the upstream.
   *
   * Note: `/api/v1/auth/status` reports whether *this request* cleared the
   * gateway's own password check. It says nothing about whether the CLI is
   * signed in to a CodeBuddy account — use `accountStatus()` for that.
   */
  async credentialStatus() {
    try {
      const res = await fetch(`${this.upstream.baseUrl}/api/v1/auth/status`, {
        headers: this.upstream.headers(),
        signal: AbortSignal.timeout(5000)
      });
      if (!res.ok) return null;
      const body = await res.json().catch(() => null);
      return body?.data ?? body;
    } catch {
      return null;
    }
  }

  /**
   * Detect whether the agent is signed in to an account.
   *
   * The HTTP API has no dedicated endpoint for this, but `/api/v1/info` exposes
   * the resolved user name, which is empty until a sign-in has happened. An
   * unauthenticated agent still accepts jobs; they simply never leave the
   * "starting..." state because the model call cannot be made.
   */
  async accountStatus() {
    try {
      const res = await fetch(`${this.upstream.baseUrl}/api/v1/info`, {
        headers: this.upstream.headers(),
        signal: AbortSignal.timeout(5000)
      });
      if (!res.ok) return null;
      const body = await res.json().catch(() => null);
      const info = body?.data ?? body;
      if (!info || typeof info !== 'object') return null;
      const userName = typeof info.userName === 'string' ? info.userName.trim() : '';
      return {
        signedIn: userName.length > 0,
        userName: userName || null,
        version: info.version ?? null,
        gatewayMode: info.gatewayMode ?? null
      };
    } catch {
      return null;
    }
  }

  /** One-shot summary used by /health, doctor and the startup log. */
  async status() {
    const [credentials, account] = await Promise.all([this.credentialStatus(), this.accountStatus()]);
    return { credentials, account };
  }

  async stop() {
    this.stopping = true;
    if (!this.child || this.child.exitCode !== null) return;
    this.log.info('stopping upstream agent service');
    this.child.kill('SIGTERM');
    const deadline = Date.now() + 5000;
    while (Date.now() < deadline && this.child.exitCode === null) await sleep(100);
    if (this.child.exitCode === null) this.child.kill('SIGKILL');
  }
}

/** Check whether the bundled CLI exists, for diagnostics. */
export function cliExists(p) {
  try {
    fs.accessSync(p, fs.constants.X_OK);
    return true;
  } catch {
    return false;
  }
}
